### ISSUE TITLE
strip carriage returns from quasi-quoter on WIndows

### ISSUE THREAD

**Issue by gregwebs** [yesodweb/shakespeare#112]
what is the downside of doing this?

The problem right now is that writing out shakespeare-text to a file ends up with "\r\r\n" since Haskell does automatic return carriage substitution.

**Comment by snoyberg** [comment]
I'm actually not sure if anything needs to be done here. @gregwebs did you have a specific example that was failing? It looks to me like CRs are already being stripped from the quasi-quoter.

**Comment by gregwebs** [comment]
The problem is writing the result of the quasi-quoter to a file. There is a GHC issue for this somewhere.

**Comment by snoyberg** [comment]
Do you have a minimal reproducing case? I'm not sure what we're trying to solve right now

**Comment by gregwebs** [comment]
Here is the ghc bug report https://ghc.haskell.org/trac/ghc/ticket/8424

**Comment by snoyberg** [comment]
This is already resolved, as seen on Windows:

```
>stack runghc qq.hs
"foo\n        bar\n        baz"
"{-# LANGUAGE QuasiQuotes #-}\r\nimport Language.Haskell.TH\r\nimport Text.Shakespeare.Text\r\nimport qualified Data.ByteString as S\r\n\r\nmain :: IO ()\r\nmain = do\r\n    print [st|foo\r\n        bar\r\n        baz|]\r\n    S.readFile \"qq.hs\" >>= print\r\n"
```
