### ISSUE TITLE
Hamlet parser chokes on ^. operator

### ISSUE THREAD

**Issue by mitchellwrosen** [yesodweb/shakespeare#133]
````
^{myWidget (someMap^.at "someKey")}
````

doesn't parse but 
````
^{myWidget (Data.Map.lookup "someKey" someMap)}
````

of course can. See https://groups.google.com/forum/#!topic/yesodweb/ftZu1qQEP3U

**Comment by snoyberg** [comment]
Closing out old issues, if still relevant please open a new one.
