### ISSUE TITLE
Data URIs parsed incorrectly

### ISSUE THREAD

**Issue by nikuda** [yesodweb/shakespeare#137]
It seems shakespeare-css doesn't handle data URIs correctly.

It will parse

    background: url(data:image/png;base64,[...]);

down to

    background: url(data:image/png;
    base64,[...]);

Firefox ignores the whole of the CSS file that rule is in. 
Chrome just ignores the rule.

shakespeare-css-1.1.0

**Comment by snoyberg** [comment]
Closing out old issues, if still relevant please open a new one.
