### ISSUE TITLE
Port to Lucid as templating engine instead of Blaze

### ISSUE THREAD

**Issue by athanclark** [yesodweb/shakespeare#149]
I find Lucid to be much more friendly in terms of modularity - for example, urls could encode the hostname in a reader monad, injected in Lucid's transformer:

```haskell
partial :: LucidT (Reader ST.Text) ()
partial = do
  hostname <- lift ask
  a_ [ href_ $ hostname <> "some/path" ] "foo"
```

You can't do that in Blaze! I'll see if I can make this happen, but I'll ping here if I run into any trouble. Thank you for this wonderful tool!!

**Comment by snoyberg** [comment]
Closing for now due to lack of activity.
