### ISSUE TITLE
Shakespeare fails to install with ghcjs on linux

### ISSUE THREAD

**Issue by dgonyeo** [yesodweb/shakespeare#154]
When I run the following commands:

```bash
cabal sandbox init
cabal install --ghcjs shakespeare
```

cabal prints out this: http://lpaste.net/2488137832325971968

It gets stuck on building shakespeare, and upon inspection the build encountered an error when looking for a file from the wrong version of blaze-html. 0.8.0.2 is the version that ended up being installed.
http://lpaste.net/4565038739402784768

I attempted installing blaze-html 0.8.0.0 and building again, but it ended up stopping on the same error with a different file from a different package.

I'm running arch

```
derek@haruko /tmp/test> uname -a
Linux haruko 3.19.2-1-ARCH #1 SMP PREEMPT Wed Mar 18 16:21:02 CET 2015 x86_64 GNU/Linux
```

with ghc 7.8.4 and ghcjs 0.1.0.

It's possible this is a bug in cabal, and not shakespeare, but I'm not sure where to poke to fix this.

**Comment by dgonyeo** [comment]
Oh, and it builds successfully with ghc on the same system, so perhaps it's a ghcjs issue. I also have built it successfully in the past with ghcjs, the only thing that has changed that I'm aware of was a `cabal update`.

Also forgot to mention, I'm using cabal version 1.22.0.0.

**Comment by snoyberg** [comment]
This looks like a GHCJS or cabal bug, I doubt there's anything we can do in
shakespeare to fix it.

**Comment by dgonyeo** [comment]
K, I'll go toss this at the ghcjs guys then.
