### ISSUE TITLE
Request: add css class-assignment to lucious/cassius

### ISSUE THREAD

**Issue by wolftune** [yesodweb/shakespeare#155]
Right now, a feature that some have wished for in CSS: The ability to make all examples of something take another class. For example, maybe I want all `.explanation-box` items to get a bootstrap class like `.col-sm-2`. Currently, that requires JavaScript or a bunch of redundancy in HTML/Hamlet files that is extraneous, tedious to change, and prone to human error.

It seems to me that it could be easy to have a syntax in lucious and cassius that would simply compile the HTML so that any items that match the quality being selected for get the assigned CSS class.

**Comment by meteficha** [comment]
You can already do something like:

```haskell
explanationBoxClass :: Text
explanationBoxClass = "explanation-box col-sm-2"
```

```
<div class="#{explanationBoxClass}">
```

If you want that support in Lucius, I don't think it's a good idea since Lucius would have to be used for Bootstrap's CSS as well.  I'd recommend using LESS in this case.

**Comment by wolftune** [comment]
I'm not sure the "have to be used for Bootstrap's CSS" argument makes sense.

All I'm saying is that the Cassius could say:

```
.explanation-box
    $class = .col-sm-2
```

And the result would be that it would render *HTML* to be `class="explanation-box col-sm-2"`. Thus, adjusting classes this way would be part of styling.

There's no reason this has to do anything at all to Bootstrap's CSS.

With the Haskell you wrote, it would not be possible to post-hoc easily add classes to existing items. It's much more hassle.

Side note: wouldn't the best Hamlet syntax for your example be `<div .#{explanationBoxClass}>`?

**Comment by meteficha** [comment]
Oh, I thought you were asking for LESS mixins on Lucius/Cassius.  I can't say I like the idea of having a class reference on Hamlet be more than a class reference, though.  Also, how would you handle a custom text being assigned at runtime?  We'd have to maintain a map of classes at runtime and parse the class attribute.  I don't think this would be a good idea.

Regarding your side note, I don't remember if that works or not :).

**Comment by wolftune** [comment]
I wasn't suggesting anything happen at runtime. My suggestion is that the *compiling* work so that Lucious/Cassius syntax actually impact the *compiling* of associated Hamlet -> HTML. To be practical, I would think this would be only in the cases where it's a single widgetfile, like `about.hamlet` and `about.cassius`. In just that case, the cassius would be used in the HTML compiling.

**Comment by snoyberg** [comment]
I think doing something more inventive like this is outside the scope of the (very simplistic) templating languages we have right now, though perhaps the combinator-library approach for generating CSS would be a good way to get this kind of functionality.
