### ISSUE TITLE
<select onchange="..."> doesn't parse

### ISSUE THREAD

**Issue by kejace** [yesodweb/shakespeare#159]
It seems that hamlet doesn't support the `onchange` field for `select`

Getting: 
```unexpected "o"
expecting ">"```

from 
```<select id="id" onchange="f(x)">```

**Comment by MaxGabriel** [comment]
I couldn't reproduce this when I added `<select id="id" onchange="f(x)">` [after line 25](https://github.com/yesodweb/yesod-scaffold/blob/ccff02fb89929826f8ee94601e4c720e7c2f2b4b/templates/homepage.hamlet#L25) of the Yesod-scaffolded homepage (using LTS Haskell 2.17). Any more details that would help reproduce this?

**Comment by kejace** [comment]
My bad. I had a newline inside the `f(x)` expression that was hidden by my text-editor.
