### ISSUE TITLE
<img> tag won't compile with 'src' attribute -- see below 

### ISSUE THREAD

**Issue by jasonzoladz** [yesodweb/shakespeare#166]
The failure refers to the "s" in `src` located in the `img` tag.  It builds when I remove the `src` attribute.

<img width="447" alt="screen shot 2015-09-20 at 4 00 28 pm" src="https://cloud.githubusercontent.com/assets/8467728/9982653/42892b0c-5fb1-11e5-9839-b14812cd6606.png">
<img width="803" alt="screen shot 2015-09-20 at 3 59 46 pm" src="https://cloud.githubusercontent.com/assets/8467728/9982654/473795da-5fb1-11e5-88b0-471b705c85c6.png">

**Comment by snoyberg** [comment]
You need to replace the dash with ASN underscore in the identifier name

**Comment by chreekat** [comment]
Perhaps this issue should be renamed to focus on improving that error message.

**Comment by jasonzoladz** [comment]
Perfect.  Thanks again for the prompt reply.  (I now vaguely recollect reading that somewhere in the book.)  
Yesod is fantastic and joy to use.  Cheers Michael.
