### ISSUE TITLE
Comment trigger error in lucius

### ISSUE THREAD

**Issue by Shimuuar** [yesodweb/shakespeare#17]
More specifically. When /_..._/ comment is placed at the end of a file yesod-devel errors when page is requested. Is some css is placed after comment error disappear.

Here is minimal CSS file which triggers error.

```
/* CRASH */
```

And error message from yesod-devel

```
Error handler errored out: InternalError "\"/* CRASH!!! */\" (line 1, column 15):\nunexpected end of input\nexpecting \"#\", \"@\", \"/*\", \",\" or \"{\""
```

**Comment by BebeSparkelSparkel** [comment]
Can comment syntax be added to the docs?
