### ISSUE TITLE
<pre> tag needs to keep new lines for empty lines but doesn't now

### ISSUE THREAD

**Issue by wolftune** [yesodweb/shakespeare#170]
When a block of text is within a `<pre>` block, it needs to be rendered exactly, including any empty lines, but hamlet currently strips them out, even when newline always is set (it respects the newline for each line with content, but still removes empty lines).

**Comment by snoyberg** [comment]
This is incorrect, hamlet is behaving correctly here. I use this exact
pattern. Hamlet never adds new semantic elements. There are CSS approaches
to the styling you want.

**Comment by wolftune** [comment]
@snoyberg I'm not actually asking for new semantic elements (I erroneously stated that initially but edited 2 min before your reply).

```
<pre>
  blah

  blah
```

renders for me as

```
<pre>blah blah</pre>
```

in HTML… which is very strange, although we seem to be seeing some difference between development and deployment settings…

**Comment by chreekat** [comment]
Yeah I just tried all combos of cabal flags and runtime arguments (using
1.2 scaffolding), and I always got the problem when running the site
locally, but in production it seems to be doing the right thing. Hm!

**Comment by snoyberg** [comment]
Maybe runtime vs production Hamlet difference. A minimal test case would be
good for this.

**Comment by chreekat** [comment]
I think this is a Snowdrift bug, not a Shakespeare bug.

To be honest there's been a variety of weird things happening in Snowdrift
wrt Hamlet generation. "$newline <foo>" seems to have no effect, for
instance. I think somebody must have changed the scaffolding code back in
time somewhere.
