### ISSUE TITLE
Allow if-then-else in message files

### ISSUE THREAD

**Issue by HairyDude** [yesodweb/shakespeare#171]
Suppose I have a localisation file with:

```
IfThenElse yn@Bool: #{if yn then "yes" else "no"}
```

If I try to use this, I get an error like:

```
src/Messages.hs:169:1:
    Not in scope: ‘if’
    Perhaps you meant ‘id’ (imported from Prelude)

src/Messages.hs:169:1: Not in scope: ‘then’

src/Messages.hs:169:1: Not in scope: ‘else’
```

Apparently the message-file parser doesn't recognise if-then-else, but tries to interpret those keywords as identifiers. I can work around this by creating a "boolean fold" function:

```
ifThenElse :: Bool -> a -> a -> a
ifThenElse yn yes no = if yn then yes else no
```

But this shouldn't be necessary.

**Comment by jezen** [comment]
This can be achieved easily enough either in Haskell or in Hamlet, so I'm struggling to see the motivation for adding conditionals directly into the internationalisation system.

_e.g._

```haskell
someHandler :: Handler ()
someHandler = do
  mr <- getMessageRender
  let theMessage = if yn then mr MsgYes else mr MsgNo
  -- …
```

or…

```
$if yn
  _{MsgYes}
$else
  _{MsgNo}
```

I'll close this for now, but let me know if there's something I've missed and we can reopen it.
