### ISSUE TITLE
Bump scientific dependency to >= 0.3.0.0

### ISSUE THREAD

**Issue by ygale** [yesodweb/shakespeare#173]
Since shakespeare 2.0.7, the module `Data.Text.Lazy.Builder.Scientific` is imported from the `scientific` package in `Text.Julius`. That module only appears in version >= 0.3.0.0 of `scientific`, so a lower bound is required.

**Comment by snoyberg** [comment]
Want to send a PR?

**Comment by ygale** [comment]
Sure with pleasure. But you probably also want to edit 2.0.7 on Hackage and add this bound.

**Comment by snoyberg** [comment]
Done
