### ISSUE TITLE
i18n in xhamlet

### ISSUE THREAD

**Issue by vandenoever** [yesodweb/shakespeare#175]
I'm using i18n in xhamlet. Currently, I use it like this:
```haskell
render <- getMessageRender
[xhamlet|
    #{render MsgHello}
|]
```

Is it possible to avoid the the `render <- getMessageRender` and `#{render` and write `_{MsgHello}` instead like it can be done with ihamlet?

**Comment by snoyberg** [comment]
If you look at the [source code](http://haddock.stackage.org/nightly-2016-01-03/shakespeare-2.0.7/src/Text-Hamlet.html#ihamlet), you can see:

```haskell
xhamlet :: QuasiQuoter
xhamlet = hamletWithSettings hamletRules xhtmlHamletSettings

ihamlet :: QuasiQuoter
ihamlet = hamletWithSettings ihamletRules defaultHamletSettings.
```

Implementing an xhamlet with i18n support should be as easy as:

```haskell
ixhamlet :: QuasiQuoter
ixhamlet = hamletWithSettings ihamletRules xhtmlHamletSettings
```

I don't see a problem with including this in shakespeare itself, if you're interested in sending a PR.

**Comment by vandenoever** [comment]
#177 is here

**Comment by chreekat** [comment]
`ixhamlet` is in now :)
