### ISSUE TITLE
Embedding a simple Html template (shamlet) inside a Hamlet template?

### ISSUE THREAD

**Issue by ajnsit** [yesodweb/shakespeare#183]
Something like this sounds reasonable -

```haskell
-- Foo uses URL interpolation
foo z = [hamlet|
  <h1> Foo
  ^{baz z}
  <a href=HomeR> Go back
|]

-- Bar does not use any URL interpolation
baz z = [shamlet|
  <h1> Bar
  ^{baz z}
|]

-- Shamlet that can be included in either Hamlet or Shamlet templates
bar z = [shamlet|
  <h2> #{show z}
|]
```

However the docs state that -

> embedding via a caret (^) which allows you to embed another template of the ***same*** type.

Which disallows this kind of code reuse. Is there any (perhaps undocumented) way to achieve this?

**Comment by snoyberg** [comment]
shamlet generates a normal Html value, so #{...} interpolation should do
the job

**Comment by ajnsit** [comment]
using #{..} generates escaped HTML instead of HTML being spliced in as is. Perhaps I'm missing some setting to allow unescaped html?

**Comment by ajnsit** [comment]
Nope, I was mistaken! #{..} works perfectly. Thanks!
