### ISSUE TITLE
hamlet does not know about void tag <source> and hence ends it with </source>

### ISSUE THREAD

**Issue by rkaminsk** [yesodweb/shakespeare#184]
The \<source\> tag should be added to Text.Hamlet.Parse.htmlEmptyTags.

As a workaround, I modified Settings.hs from the scaffolded site. This works for the widgetFile function then. Defining a QuasiQuoter like whamlet was even more complicated.

A list of all void tags is here: https://www.w3.org/TR/html-markup/syntax.html

```
widgetFileSettings :: WidgetFileSettings
widgetFileSettings = def·
    { wfsHamletSettings = defaultHamletSettings
        { hamletCloseStyle = hamletCloseStyle defaultHamletSettings·
            { hamletCloseStyle = close }
        }
    }
    where close "source" = NoClose
          close tag = hamletCloseStyle defaultHamletSettings tag
```

**Comment by psibi** [comment]
@rkaminsk Are you interested in sending a patch for this ?

**Comment by rkaminsk** [comment]
There you go. I just added some more tags to the htmlEmptyTags list.

**Comment by psibi** [comment]
Fixed in https://github.com/yesodweb/shakespeare/pull/185
