### ISSUE TITLE
<pre> contents should never be formatted

### ISSUE THREAD

**Issue by chreekat** [yesodweb/shakespeare#193]
Behavior captured in shakespeare's tests seems to indicate that `$newline [always|never|text]` intentionally has different effects on the contents of a \<pre> block. It seems that that should never be the case; whitespace should always be preserved.

**Comment by snoyberg** [comment]
Can you clarify which tests indicate this?

**Comment by chreekat** [comment]
"avoid newlines" and "manual linebreaks"

https://github.com/yesodweb/shakespeare/blob/master/test/Text/HamletSpec.hs#L409

See also https://github.com/chreekat/shakespeare/commit/970e744be225649c157ea073f86008bf2dbb3707

**Comment by snoyberg** [comment]
But it doesn't look like this has anything to do with `pre`. If I do the same thing with a `p` tag, isn't the result the same as with `pre`?

**Comment by chreekat** [comment]
My assertion is that it *should* be different. If Hamlet eats whitespace, it becomes impossible to display it as it was typed.

>  The HTML \<pre> element (or HTML Preformatted Text) represents preformatted text.... Whitespace inside this element is displayed as typed.
> —— https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre

Is there a situation where munging the content of a \<pre> is a good thing?

**Comment by snoyberg** [comment]
I read the entire contents of this issue in exactly the opposite way. What you're saying now makes more sense.

I think the current behavior is far more consistent than special casing a single element.

**Comment by chreekat** [comment]
K, no problem.
