### ISSUE TITLE
Parser fails without space between class and ID (Hamlet)

### ISSUE THREAD

**Issue by terickson001** [yesodweb/shakespeare#197]
Having quickly looked through the parser, it seems to intentionally throw an error if there is no space between the end of a class and the beginning of an ID. For example:

- `<div .foo#bar>`: Fails
- `<div #foo.bar>`: Succeeds

I would've assumed it was just an oversight in the parser, but it deliberately checks for that exact scenario. Is there a reason a class cannot touch a hash? and why is the opposite 
(^ tag 2) valid?

Sorry if i've overlooked some detail explaining this, I just found the inconsistency strange and figured it wasn't intentional.

**Comment by snoyberg** [comment]
I'm not aware of any reason for this specific quirk, and I'd be open to a
PR to fix it, assuming it doesn't introduce regressions.

**Comment by snoyberg** [comment]
Fixed by PR #198, thanks!

**Comment by ygale** [comment]
@snoyberg wrote:

> I'd be open to a PR to fix it, assuming it doesn't introduce regressions.

The PR has already been merged. But it does cause a regression, #200.
