### ISSUE TITLE
New contentHash parser breaks hash hrefs

### ISSUE THREAD

**Issue by bermanjosh** [yesodweb/shakespeare#200]
I think #198 breaks the following:
`<a #logoutbutton href=#>`

It returns the following error:

> unexpected "h"
> expecting ">"

**Comment by snoyberg** [comment]
Pinging @terickson001, I'm probably going to have to revert the change.

@bermanjosh interested in sending a PR for an additional test case to prevent this regression in the future?

**Comment by terickson001** [comment]
Sorry about that, overlooked Attributes a bit when I was testing. Should be fixed in this PR.

**Comment by joeyh** [comment]
I'm getting what seems like the same kind of reversion with 2.0.12

<a .btn .btn-default data-toggle="collapse" data-target="##{ident}">#{toggle}</a>

unexpected "d"
    expecting ">"

I think the 'd' is from data-target.

**Comment by terickson001** [comment]
@joeyh That is fixed in PR #201, I just tested it to be sure.

**Comment by bermanjosh** [comment]
@terickson001 Thanks! 
@snoyberg Ok if I close the issue?

**Comment by snoyberg** [comment]
Yes, sounds good, I'll merge and release shortly.
