### ISSUE TITLE
`Block` is not exported

### ISSUE THREAD

**Issue by tolysz** [yesodweb/shakespeare#203]
Would it be possible to re-export 
```
Text.Css
Text.CssCommon
```
Possible via some internal? Or maybe all of the `other`? Allowing to build new quotes without copying all the code?

If we just do the first some `yesod` based application could be buildable with `ghc-8.0.1`?
NB. there is a `ghc` but which at times prevents to use type constructors from hidden packages.

**Comment by snoyberg** [comment]
I'm OK with exposing this from a .Internal module. Want to send a PR? I'm
not quite sure what your use cases are here.
