### ISSUE TITLE
Interpolated tags force a line break in Hamlet

### ISSUE THREAD

**Issue by JaSpa** [yesodweb/shakespeare#208]
The following small program …

```haskell
{-# LANGUAGE QuasiQuotes #-}
import Text.Blaze.Renderer.String
import Text.Hamlet

x = [shamlet|<a href=#>Foo|]
y = [shamlet|Foo #{x}!|]
main = putStrLn $ renderMarkup y
```

… generates this output:

```html
Foo <a href="#">Foo</a>
!
```

But I would expect this output:

```html
Foo <a href="#">Foo</a>!
```

Which makes quite a difference, because with the current behavior a space is displayed between the link and the punctation which I'm not able to get rid of.

**Comment by ncaq** [comment]
you can  `$newline never`

~~~hs
{-# LANGUAGE QuasiQuotes #-}
import           Text.Blaze.Renderer.String
import           Text.Hamlet

x = [shamlet|$newline never
<a href=#>Foo|]
y = [shamlet|Foo #{x}!|]
main = putStrLn $ renderMarkup y
~~~

**Comment by JaSpa** [comment]
Oh my god, I thought I had tried this, I guess I tried `$newline never` everywhere expect there … never mind, thanks!
