### ISSUE TITLE
quasiquoter eats hash characters at the end of each line

### ISSUE THREAD

**Issue by gbwey** [yesodweb/shakespeare#214]
On a windows machine using ghc 8.02

[st|#|] renders as ""

[st|#
aaa#
bbb#
|]
drops the hash characters at the end of each line.

**Comment by snoyberg** [comment]
Hashes at the end are generally stripped in Shakespeare. It's a mechanism
to allow trailing whitespace in templates.

**Comment by gbwey** [comment]
Thanks!
