### ISSUE TITLE
Constructor for lists `(:)` does not work in hamlet template

### ISSUE THREAD

**Issue by EugineKosenko** [yesodweb/shakespeare#222]
The next code snippet 

```
$case [1, 2, 3]
   $of x:xs
      #{x}
      $forall y <- xs
         , #{y}
```
causes an error:
```
unexpected ":"
expecting letter or digit, "_", "'", " ", "@", "," or ")"
```
The pattern of empty list [] is supported, but the support for compound list constructor (:) is not. Is it a bug or a feature? It is possible to make a workaround, using `$if` clause, but the case pattern seems to be more natural here.

**Comment by ncaq** [comment]
relation #147 ?
I read to can use `:` at old shakespeare.

# workaround 2

use uncons.

~~~hs
{-# LANGUAGE QuasiQuotes #-}

import           Data.List
import           Text.Blaze.Html.Renderer.Pretty (renderHtml)
import           Text.Hamlet

main :: IO ()
main = print $ renderHtml
  [shamlet|
$case uncons example
  $of Just (x, xs)
    #{x}
    $forall y <- xs
      , #{y}
|]
  where example :: [Int]
        example = [1, 2, 3]
~~~

**Comment by EugineKosenko** [comment]
Yes, the problem is the same, but in my case the pattern `(:) x xs` doesn't work too.

I will use your workaround, but I think the situation is not proper...
