### ISSUE TITLE
Variable interpolation in Julius?

### ISSUE THREAD

**Issue by pythonissam** [yesodweb/shakespeare#226]
Currently, there's no `ToJavascript` instance of `String` and `Text`. I've read [this blog post](https://www.yesodweb.com/blog/2012/11/updates-julius-interpolation). It says:

> Down the road, it will likely make sense to add in ToJavascript instances for common types which first convert to JSON. However, doing so in this first release would mean that old code would silently change its semantics.

Still need to consider backwards compatibility?

**Comment by snoyberg** [comment]
I think I'd be OK with such a change at this point, PR welcome.

**Comment by pythonissam** [comment]
OK, I'll submit it.
