### ISSUE TITLE
Conditional comments in Hamlet

### ISSUE THREAD

**Issue by janvogt** [yesodweb/shakespeare#235]
Hamlet removes HTML comments, including [conditional comments](https://en.wikipedia.org/wiki/Conditional_comment). So sth. like

```html
<!--[if IE 6]>
<p>You are using Internet Explorer 6.</p>
<![endif]-->
```

does not work.

Is it possible to exempt these like it has been done for `<!-- #SSI -->`?

I guess it would be a little bit more involved to achieve sth. like this.

```
<!--[if IE 6]>
  <p>You are using Internet Explorer 6.
```

I don't feel confident enough in TemplateHaskell to try implementing it myself. So right now, I am doing this as a workaround:

```
<p><!--[if IE 6]><p>You are using Internet Explorer 6.</p><![endif]-->
```

**Comment by snoyberg** [comment]
I haven't tested this myself, but does putting a backslash at the beginning
of the line work?

**Comment by janvogt** [comment]
@snoyberg prefect! This works. Thanks a lot.

**Comment by snoyberg** [comment]
You're welcome, my pleasure!

**Comment by Javran** [comment]
Just want to note that this is also useful for other things that utilize HTML comments.

For example [knockoutjs's virtual elements](https://knockoutjs.com/documentation/custom-bindings-for-virtual-elements.html). This would work:

```
\<!-- ko foreach: items -->
  <li data-bind="text: $data"></li>
\<!-- /ko -->
```

If I read the code right, `\` would escape until end of that line.
