### ISSUE TITLE
Caret Interpolation with justVarInterpolation

### ISSUE THREAD

**Issue by akazik** [yesodweb/shakespeare#242]
Using ^{..} in an QuasiQuoter with justVarInterpolation fails because the url renderer is used (even though it shouldn't).

To fix this replace contentsToShakespeare's contentToBuilder ContentMix case with:
```haskell
return $
  if justVarInterpolation rs
    then derefToExp [] d
    else derefToExp [] d `AppE` VarE r
```

**Comment by snoyberg** [comment]
Are you interested in sending a PR which includes a regression test?
