### ISSUE TITLE
CSS Math

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [yesodweb/shakespeare#248]
Is there anyway to allow math to be performed in the Lucius and Cassius files?

```cassius
@elemWidth
@elemMargin

div
  width: #{elemWidth + 2 * elemMargin}
```

**Comment by jezen** [comment]
Yes, you can indeed do this, but I think you'll need to declare those values you are operating on in Haskell-land.

Something like this will work:

```haskell
-- in some Haskell file…
elemWidth = 800

elemMargin = 200
```

```
/* some Cassius snippet */
div
  width: #{elemWidth + 2 * elemMargin}
```
