### ISSUE TITLE
Julius: async function cannot be parsed

### ISSUE THREAD

**Issue by schnecki** [yesodweb/shakespeare#250]
Hi,

Julius does not accept async functions, e.g.

    async function test() {}

becomes 

    async;function test(){}

in the generated JavaScript file. Note the semicolon. This causes following error

    ReferenceError: async is not defined

in WebBrowsers. It worked in previous versions, but I cannot say which ones unfortunately. Currently I am using:

    [22:37:51 schnecki devboardserver]$ stack ls dependencies --separator '-' | grep shakes
    shakespeare-2.0.23
    [22:38:05 schnecki devboardserver]$ stack ls dependencies --separator '-' | grep yesod
    classy-prelude-yesod-1.5.0
    yesod-1.6.0
    yesod-auth-1.6.8
    yesod-core-1.6.17
    yesod-form-1.6.7
    yesod-newsfeed-1.6.1.0
    yesod-persistent-1.6.0.4
    yesod-static-1.6.0.1

Manuel

**Comment by snoyberg** [comment]
Can you provide a minimal repro as a Stack script?

**Comment by schnecki** [comment]
I couldn't actually. But after spending some hours on the problem I figured that it depends on the code just before the call to widgetFile (Reload and NoReload behave the same for this thing). 

    getDataR :: Handler Html
    getDataR = do
      imageKeysInt <- runDB (fmap (fromIntegral . fromSqlKey . entityKey) <$> selectList [] [LimitTo 3, Desc ImageId])
      let imageKeysInt = [] :: [Integer]
      let imageKeys = toJSON (imageKeysInt :: [Integer])
      annotNames <- fmap (objectTypeName . entityVal) <$> runDB (selectList [] [Asc ObjectTypeName])
      let annotNames = [] :: [Text]
      let annotNamesJson = toJSON annotNames
      defaultLayout $ do
        setTitle $ toHtml ("Incoming Data" :: Text)
        $(widgetFile "data/incoming")

If I comment out any of the two lines that define the empty list, the async compilation error occurs. So how do I use these two variables:

    data/incoming.hamlet
    ---------------------------
              ...
              $forall name <- annotNames
                ...
                    <input class="form-check-input"  #hide-annotation-#{name} .annotations-checkbox type=checkbox onclick="showHideAnnotation(this, '#{name}')"> Hide #{name} annotation

Removing these lines has no effect.

    data/incoming.julius
    -------------------------
    var startKeys = JSON.parse("#{imageKeys}");
    var annotNames = JSON.parse('#{annotNamesJson}');
    ...

It gets even more confusing. If I delete i) all lines before `defaultLayout`, empty the hamlet and the change the lucius to only contain `async function test() {}`, or ii) just change the julius to contain `async function test() {}` it does *not* work again, and finally iii) if I add something in the list of `imageKeysInt`, e.g. `let imageKeysInt = [1] :: [Integer]` it does not work again. But these things are all reproducible. I don't understand why it worked before, nor what this all has to do with the compilation process of the julius. 

Am I using the interpolation wrong? If so, why doesn't it work for the empty files? Thanks a lot for your help @snoyberg

**Comment by snoyberg** [comment]
I'm really not sure, I'd need to see something more self-contained. I haven't seen the JSON.parse approach you're using above, it makes me think there may be a character escaping issue at play, but I'm really not certain.

**Comment by schnecki** [comment]
Hmm well I understand. I don't really know how to reproduce it myself. As that part of the code will be deleted I guess I just close that issue, but one more question before that: What is the proper way of getting a list of `a`'s into Julius. By doing a `forall`? I see the point of doing so for Hamlet, but in Javascript not really.

**Comment by snoyberg** [comment]
I would recommend converting into aeson's `Value` via `toJSON`.

**Comment by schnecki** [comment]
Ok I see. Thx a lot :+1:
