### ISSUE TITLE
Misleading error message when using infix operators

### ISSUE THREAD

**Issue by periodic** [yesodweb/shakespeare#56]
I get the following error with a snippet of hamlet parsed with [whamlet|..]

    Yesod/Widget/Pager.hs:65:8:
        Exception when trying to run compile-time code:
      "
    $if (>) m 1
        <div class=#{cssClass opts}>
            <ul>
                $if showFirst opts
                    <li.first.prev :p <= 1:.disabled>
                        <a href=#{urlGenerator opts 0}>
                            First
                $if showPrev opts
                    <li.prev :p <= 1:.disabled>
                        <a href=#{urlGenerator opts prevP}>
                            Prev
                $forall n <- pageNums
                    <li :n == p:.active>
                        <a href=#{urlGenerator opts n}>
                            #{n}
                $if showNext opts
                    <li.next :p >= m:.disabled>
                        <a href=#{urlGenerator opts nextP}>
                            Next
                $if showLast opts
                    <li.last.next :p >= m:.disabled>
                        <a href=#{urlGenerator opts m}>
                            Last
    " (line 6, column 32):
    unexpected ":"
    expecting ">"

If I switch it to `<li.first.prev :(<=) p 1:.disabled>` then the error goes away.  The error should be that the infix operator is invalid, as a colon-conditional is valid at that location.  Note that the column location, 32, refers to the first colon of the conditional.

**Comment by snoyberg** [comment]
Closing out old issues, if still relevant please open a new one.
