### ISSUE TITLE
Better type safety for URL interpolation

### ISSUE THREAD

**Issue by ezyang** [yesodweb/shakespeare#82]
Presently, arbitrary strings can be placed in src/href attributes using ``#{}`` interpolation.  This represents a security risk if these strings come from a user.

In Ur/Web, this issue is alleviated by having an abstract URL datatype which user strings can be "blessed" into. This process performs validation; for example, Ur/Web can have an arbitrary complicated "URL policy", and bless fails with a runtime error if the URL passed to it violates that policy. Hamlet should have a similar facility, with a policy that at least does something sensible about non-HTTP URI schemes.

**Comment by snoyberg** [comment]
Closing out old issues, if still relevant please open a new one.
