### ISSUE TITLE
More general `mkMessageFor` function.

### ISSUE THREAD

**Issue by piyush-kurur** [yesodweb/shakespeare#87]
In shakespeare-i18n: I would like a general version of
`mkMessageFor` functions. Here is the signature of what I
expect.

```haskell
mkMessageGen :: TypeQ    -- ^ master type
             -> TypeQ    -- ^ The message type
             -> FilePath -- ^ Translation files
             -> Lang     -- ^ Default language
             -> DecsQ
```

The function should behave similar to mkMessageFor but should take
general types instead of specific types. A use case is the following:

A use case: 

A generic wiki that supports i18n  and can be embedded as a subsite of a yesod
application. For example I might have a message type like

```haskell
data WikiAction = Edit
                | Delete
                | Rename
```
I also want to maintain the translation files in the wiki library so
that the user of my library can get full i18n support without much
effort (she can support languages that that she does not know
herself). This means that I need a render message instance in the
library itself.

```haskell
instance RenderMessage master WikiAction where
         renderMessage ....
```

I cannot use `mkMessageFor` as I donot know the master site type in the
library.

I should also add that one can support the above feature with current interface
indirectly as follows:

(1) The library supports a set of translation files.

(2) It exports the path to those translation files (By making use of
    the Paths_pkg module).

The user can then use `mkMessageFor` with the path exposed by the
library. This should do the trick but I find this a little contrived.

**Comment by eggonabull** [comment]
I also wanted the ability to use the shakespeare mkMessage* functions with yesod subsites.  I hacked in a very rough support for this by overwriting mkMessage common with the following.
```
mkMessageCommon genType prefix postfix master dt' folder lang = do
    files <- qRunIO $ getDirectoryContents folder
    let dt = head $ words dt'
    let files' = filter (`notElem` [".", ".."]) files
    (_files', contents) <- qRunIO $ fmap (unzip . catMaybes) $ mapM (loadLang folder) files'
#ifdef GHC_7_4
    mapM_ qAddDependentFile $ concat _files'
#endif
    let contents' = Map.toList $ Map.fromListWith (++) contents
    sdef <-
        case lookup lang contents' of
            Nothing -> error $ "Did not find main language file: " ++ unpack lang
            Just def -> toSDefs def
    mapM_ (checkDef sdef) $ map snd contents'
    let mname = mkName $ dt ++ postfix
        (instanceCtx, instanceType) = case words master of
          (tNameS:[]) -> ([], ConT $ mkName tNameS)
          (tNameS:vNameS:[]) -> let vName = mkName vNameS in
            (
              [ClassP (mkName tNameS) [VarT vName]]
              , VarT vName
            )
          _ -> error "Couldn't "
          
    c1 <- fmap concat $ mapM (toClauses prefix dt) contents'
    c2 <- mapM (sToClause prefix dt) sdef
    c3 <- defClause
    return $
     ( if genType 
       then ((DataD [] mname [] (map (toCon dt) sdef) []) :)
       else id)
        [ InstanceD
            instanceCtx
            (ConT ''RenderMessage `AppT` instanceType `AppT` ConT mname)
            [ FunD (mkName "renderMessage") $ c1 ++ c2 ++ [c3]
            ]
        ]
```

**Comment by snoyberg** [comment]
Closing out old issues, if still relevant please open a new one.
